/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiOcidRouteImport } from './routes/api/ocid'
import { Route as ApiTelemetryRouteImport } from './routes/api/telemetry'
import { Route as ApiWifiRouteImport } from './routes/api/wifi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOcidRoute = ApiOcidRouteImport.update({
  id: '/api/ocid',
  path: '/api/ocid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelemetryRoute = ApiTelemetryRouteImport.update({
  id: '/api/telemetry',
  path: '/api/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWifiRoute = ApiWifiRouteImport.update({
  id: '/api/wifi',
  path: '/api/wifi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ocid': typeof ApiOcidRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/wifi': typeof ApiWifiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ocid': typeof ApiOcidRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/wifi': typeof ApiWifiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ocid': typeof ApiOcidRoute
  '/api/telemetry': typeof ApiTelemetryRoute
  '/api/wifi': typeof ApiWifiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/ocid' | '/api/telemetry' | '/api/wifi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ocid' | '/api/telemetry' | '/api/wifi'
  id: '__root__' | '/' | '/api/ocid' | '/api/telemetry' | '/api/wifi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiOcidRoute: typeof ApiOcidRoute
  ApiTelemetryRoute: typeof ApiTelemetryRoute
  ApiWifiRoute: typeof ApiWifiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ocid': {
      id: '/api/ocid'
      path: '/api/ocid'
      fullPath: '/api/ocid'
      preLoaderRoute: typeof ApiOcidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telemetry': {
      id: '/api/telemetry'
      path: '/api/telemetry'
      fullPath: '/api/telemetry'
      preLoaderRoute: typeof ApiTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wifi': {
      id: '/api/wifi'
      path: '/api/wifi'
      fullPath: '/api/wifi'
      preLoaderRoute: typeof ApiWifiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiOcidRoute: ApiOcidRoute,
  ApiTelemetryRoute: ApiTelemetryRoute,
  ApiWifiRoute: ApiWifiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
